services:

  # Backend API
  smart-brain-api:
    container_name: backend
    build: ./
    working_dir: /usr/src/smart-brain-api
    command: npm start
    environment:
      DB_URI: postgres://guillaume:password@postgres:5432/smart-brain-docker
      REDIS_URI: redis://redis:6379
    depends_on:
      - postgres
      - redis
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/smart-brain-api
  
  # PostgreSQL
  postgres:
    container_name: postgres
    build: ./postgres
    environment:
      POSTGRES_USER: guillaume
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smart-brain-docker
    ports:
      - 5433:5432

  # Redis
  redis:
    container_name: redis
    image: redis:7.0.8
    command: redis-server
    ports:
      - 6379:6379